In [3]:
import numpy as np

In [5]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [10]:
n2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
n2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [13]:
n3 = np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
n4 = np.full((4,5),6)
n4

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [17]:
n5 = np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
n6 = np.arange(10,51,5)
n6

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
n7 = np.random.randint(10,50,5)
n7

array([12, 16, 39, 14, 34])

In [23]:
n8 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
n8.shape

(2, 5)

In [25]:
n8.shape = (5,2)
n8

array([[ 1,  2],
       [ 3,  4],
       [ 5, 10],
       [20, 30],
       [40, 50]])

In [31]:
n9 = n2.transpose()
n9

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

# Joining NumPy Arrays

In [32]:
import numpy as np
n1 = np.array([1,2,3,4])
n2 = np.array([10,20,30,40])

In [35]:
np.vstack((n1,n2))

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [36]:
np.hstack((n1,n2))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [37]:
np.column_stack((n1,n2))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

# Intersection and Differences

In [38]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [41]:
np.intersect1d(n1,n2)

array([50, 60])

In [43]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [44]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

# Mathematics

In [46]:
import numpy as np
n1 = np.array([10,20])
n2 = np.array([30,40])

In [48]:
np.sum((n1,n2))

100

In [49]:
np.sum((n1,n2),axis=0)

array([40, 60])

In [50]:
np.sum((n1,n2),axis=1)

array([30, 70])

In [53]:
n3 = np.array([10,20,30])
n3 = n3+5
n3

array([15, 25, 35])

In [54]:
n3 = np.array([10,20,30])
n3 = n3-5
n3

array([ 5, 15, 25])

In [55]:
n3 = np.array([10,20,30])
n3 = n3*5
n3

array([ 50, 100, 150])

In [56]:
n3 = np.array([10,20,30])
n3 = n3/5
n3

array([2., 4., 6.])

In [59]:
n4 = np.array([10,20,30,40,50,60])
np.mean(n4)

35.0

In [60]:
np.median(n4)

35.0

In [61]:
np.std(n4)

17.07825127659933

# Save and Load

In [62]:
n1 = np.array([10,20,30,40,50,60])
np.save('check',n1)

In [63]:
n2 = np.load('check.npy')
n2

array([10, 20, 30, 40, 50, 60])